<a href="https://colab.research.google.com/github/muralikrishnan2022/CTF_Data_MIC/blob/main/MIC_CTF2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Assuming you have a DataFrame named 'df'
df= pd.read_csv('/content/FIFA 19 data.csv')

# Example using a DataFrame
num_rows, num_columns = df.shape

print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_columns}")

Number of Rows: 17219
Number of Columns: 82

In [ ]:
df

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,International Reputation,...,GKKicking,GKPositioning,GKReflexes,Release Clause,DOB,Height,Weight,Right Foot,Offensive Work Rate,Defensive Work Rate
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,565000.0,2202,5.0,...,15.0,14.0,8.0,226500000.0,1987-06-24,170,72,False,Medium,Medium
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,405000.0,2228,5.0,...,15.0,14.0,11.0,127100000.0,1985-02-05,187,83,True,High,Low
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,290000.0,2143,5.0,...,15.0,15.0,11.0,228100000.0,1992-02-05,175,68,True,High,Medium
3,De Gea,27,Spain,91,93,Manchester United,72000000.0,260000.0,1471,4.0,...,87.0,88.0,94.0,138600000.0,1990-11-07,193,76,True,Medium,Medium
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000000.0,355000.0,2281,4.0,...,5.0,10.0,13.0,196400000.0,1991-06-28,181,70,True,High,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17214,S. Griffin,18,Republic of Ireland,47,67,Waterford FC,60000.0,1000.0,1325,1.0,...,12.0,7.0,13.0,153000.0,1999-12-31,173,64,True,Medium,Medium
17215,K. Fujikawa,19,Japan,47,61,JÃºbilo Iwata,60000.0,1000.0,1333,1.0,...,6.0,11.0,8.0,113000.0,1998-07-24,171,66,True,Medium,Medium
17216,J. Young,18,Scotland,47,62,Swindon Town,60000.0,1000.0,1203,1.0,...,12.0,12.0,11.0,143000.0,1999-07-31,175,71,False,Medium,Medium
17217,J. Lundstram,19,England,47,65,Crewe Alexandra,60000.0,1000.0,1307,1.0,...,7.0,8.0,9.0,143000.0,1999-02-19,176,61,True,Medium,Medium
17218,B. Worman,16,England,47,67,Cambridge United,60000.0,1000.0,1189,1.0,...,10.0,6.0,13.0,165000.0,2001-08-30,172,67,True,Medium,Medium

In [ ]:
rated_80_players = df[df['Overall'] == 80]
total_rated_80_players = len(rated_80_players)
print(f'Total number of 80-rated players in FIFA 19: {total_rated_80_players}')

Total number of 80-rated players in FIFA 19: 143

In [ ]:
# Filter Spanish players (assuming 'Nationality' is the column with nationality information)
spanish_players = df[df['Nationality'] == 'Spain']

# Get the total number of Spanish players
total_spanish_players = len(spanish_players)

# Print the result
print(f'Total number of Spanish players in FIFA 19: {total_spanish_players}')

Total number of Spanish players in FIFA 19: 1015

In [ ]:
filtered_players = df[(df['Value'] >= 10000) & (df['Value'] <= 20000)]

# Check if there are players in the specified range
if not filtered_players.empty:
    # Calculate the mean value of players within the range
    mean_value = round(filtered_players['Value'].mean(), 2)
    print(f'Average value of players between 10,000 and 20,000 coins: {mean_value}')
else:
    print('No players found in the specified value range.')

Average value of players between 10,000 and 20,000 coins: 15714.29

In [ ]:
# Filter players within the specified value range (1000 to 2000)
filtered_players = df[(df['Value'] >= 10000) & (df['Value'] <= 20000)]

filtered_players

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,International Reputation,...,GKKicking,GKPositioning,GKReflexes,Release Clause,DOB,Height,Weight,Right Foot,Offensive Work Rate,Defensive Work Rate
12396,P. Gori,38,Italy,63,63,Benevento,20000.0,1000.0,1101,1.0,...,64.0,69.0,59.0,32000.0,1980-05-10,189,83,True,Medium,Medium
12639,S. Bywater,37,England,63,63,Burton Albion,20000.0,1000.0,1126,1.0,...,55.0,68.0,55.0,35000.0,1981-06-07,185,81,True,Medium,Medium
12657,M. McNulty,37,Republic of Ireland,63,63,Cork City,20000.0,1000.0,1021,1.0,...,54.0,62.0,66.0,31000.0,1980-10-13,185,74,True,Medium,Medium
12658,L. Corti,37,Argentina,63,63,San MartÃ­n de San Juan,20000.0,2000.0,866,1.0,...,56.0,74.0,63.0,29000.0,1981-01-29,180,77,True,Medium,Medium
13502,F. Al Shammari,37,Saudi Arabia,61,61,Al Fayha,20000.0,2000.0,979,1.0,...,55.0,59.0,63.0,33000.0,1981-05-05,181,75,True,Medium,Medium
13779,Y. GutiÃ©rrez,37,Mexico,61,61,Club Necaxa,20000.0,1000.0,1068,1.0,...,63.0,60.0,57.0,34000.0,1981-03-15,189,86,True,Medium,Medium
14200,Yang Jun,37,China PR,60,60,Tianjin Quanjian FC,10000.0,2000.0,970,1.0,...,60.0,59.0,57.0,22000.0,1981-06-10,187,78,True,Medium,Medium
14545,M. Gurski,39,Germany,60,60,SpVgg Unterhaching,10000.0,1000.0,942,1.0,...,38.0,62.0,60.0,15000.0,1979-03-21,189,89,True,Medium,Medium
14812,M. Tyler,41,England,59,59,Peterborough United,10000.0,1000.0,1031,1.0,...,54.0,63.0,55.0,18000.0,1977-04-02,183,83,True,Medium,Medium
14884,S. Shearer,37,Scotland,59,59,Oxford United,10000.0,1000.0,1039,1.0,...,52.0,60.0,60.0,18000.0,1981-02-15,191,89,False,Medium,Medium
14961,S. Bengriba,37,France,59,59,Grenoble Foot 38,20000.0,1000.0,1528,1.0,...,11.0,12.0,12.0,35000.0,1980-09-24,176,71,False,Medium,Medium
15011,D. Nasu,36,Japan,59,59,Vissel Kobe,20000.0,1000.0,1396,1.0,...,11.0,7.0,9.0,25000.0,1981-10-10,180,77,True,Low,High
15301,J. Inamoto,38,Japan,58,58,Hokkaido Consadole Sapporo,20000.0,1000.0,1613,1.0,...,8.0,11.0,16.0,25000.0,1979-09-18,181,77,True,Low,High
15369,K. Fegrouche,36,Morocco,58,58,IK Sirius,20000.0,1000.0,1008,1.0,...,55.0,59.0,58.0,25000.0,1982-02-14,185,76,True,Medium,Medium
15507,C. MÃ¥nsson,37,Sweden,58,58,Kristiansund BK,10000.0,1000.0,1070,1.0,...,57.0,59.0,59.0,13000.0,1981-01-04,188,88,True,Medium,Medium
15547,B. LekstrÃ¶m,37,Sweden,58,58,Hammarby IF,10000.0,1000.0,1011,1.0,...,56.0,60.0,58.0,13000.0,1981-02-19,191,86,True,Medium,Medium
15559,P. van der Vlag,40,Netherlands,58,58,FC Emmen,10000.0,1000.0,965,1.0,...,59.0,61.0,51.0,15000.0,1977-12-05,185,76,True,Medium,Medium
15604,C. Weale,36,England,57,57,Exeter City,10000.0,1000.0,1117,1.0,...,57.0,56.0,56.0,18000.0,1982-02-09,188,84,False,Medium,Medium
15823,K. Kitamoto,36,Japan,57,57,Vissel Kobe,10000.0,1000.0,1175,1.0,...,8.0,8.0,12.0,13000.0,1981-09-18,181,78,True,Low,Medium
15851,A. Al Basisi,40,Saudi Arabia,57,57,Ohod Club,10000.0,1000.0,1066,1.0,...,54.0,58.0,57.0,17000.0,1977-12-11,184,86,True,Medium,Medium
15880,K. Stamatopoulos,38,Canada,57,57,AIK,10000.0,1000.0,1001,1.0,...,54.0,57.0,56.0,13000.0,1979-08-28,188,80,False,Medium,Medium
16024,K. Ogi,35,Japan,56,56,Vissel Kobe,20000.0,1000.0,843,1.0,...,48.0,57.0,58.0,25000.0,1983-05-05,185,76,True,Medium,Medium
16160,Y. Uekusa,35,Japan,56,56,Shimizu S-Pulse,20000.0,1000.0,1303,1.0,...,59.0,55.0,65.0,25000.0,1982-07-02,186,80,True,Medium,Medium
16396,Y. Nishibe,37,Japan,55,55,Shimizu S-Pulse,10000.0,1000.0,823,1.0,...,56.0,59.0,56.0,13000.0,1980-12-01,187,79,True,Medium,Medium
16497,Y. Kurihara,34,Japan,54,54,Yokohama F. Marinos,20000.0,1000.0,1130,1.0,...,10.0,13.0,10.0,25000.0,1983-09-18,184,80,True,Low,Medium
16505,G. Maley,35,Scotland,54,54,Livingston FC,20000.0,1000.0,845,1.0,...,48.0,59.0,50.0,35000.0,1982-08-03,188,90,True,Medium,Medium
16601,S. Ono,38,Japan,54,54,Hokkaido Consadole Sapporo,20000.0,1000.0,1416,2.0,...,9.0,6.0,11.0,25000.0,1979-09-27,175,76,True,Medium,Low
16769,J. McCombe,35,England,53,53,Lincoln City,10000.0,2000.0,1000,1.0,...,12.0,11.0,14.0,18000.0,1983-01-01,196,79,True,Medium,Medium
16813,F. Nicastro,36,Italy,53,53,NeuchÃ¢tel Xamax,10000.0,1000.0,867,1.0,...,58.0,58.0,52.0,15000.0,1981-11-24,183,78,True,Medium,Medium
16938,Zhou Ting,39,China PR,52,52,Dalian YiFang FC,10000.0,1000.0,1473,1.0,...,7.0,15.0,6.0,22000.0,1979-02-05,185,74,True,Medium,Low
17081,J. Miszczuk,27,Poland,50,50,Jagiellonia BiaÅystok,20000.0,1000.0,941,1.0,...,49.0,48.0,51.0,27000.0,1990-08-06,186,76,True,Medium,Medium
17090,A. Suzuki,31,Japan,50,50,Yokohama F. Marinos,20000.0,1000.0,820,1.0,...,54.0,52.0,54.0,25000.0,1987-04-13,184,80,True,Medium,Medium
17094,Teng Shangkun,27,China PR,50,51,Tianjin TEDA FC,20000.0,1000.0,868,1.0,...,55.0,45.0,53.0,45000.0,1991-01-10,186,78,True,Medium,Medium
17113,Sun Qibin,26,China PR,50,52,Tianjin Quanjian FC,20000.0,2000.0,843,1.0,...,51.0,48.0,50.0,45000.0,1991-11-06,192,80,True,Medium,Medium
17193,Y. Uchimura,33,Japan,48,48,Hokkaido Consadole Sapporo,20000.0,1000.0,1262,1.0,...,7.0,15.0,15.0,25000.0,1984-08-24,174,67,True,Medium,Low

In [ ]:
average_overall_score = filtered_players['Overall'].mean()

print(f"\nAverage Overall Score: {average_overall_score:.2f}")

Average Overall Score: 56.66

In [ ]:
import pandas as pd

# Load the dataset
hp_df = pd.read_csv('/content/harry_potter.csv')

hp_df

,ID,Intelligence,Blood Status,Loyalty,Gender,What are you curious about?,Affinity to Dark Arts,Magic Transportation Model,Height,Preferred Goblet Potion,"If you were a principal, how would you choose your students?",Species,Preferred Element,Kindness,House
0,1,30.0,Muggle Born,37.0,F,World after we die,51.94,Apparition,169.42,The Golden Potion,By a difficult exam,Centaurs,NaN,69.50,Gryffindor
1,2,32.0,Pure Blood,42.0,F,World after we die,54.00,Apparition,183.53,Potion that smells of plums and chocolates,I choose without preferences,Humans,NaN,49.61,Slytherine
2,3,32.0,Pure Blood,38.0,F,World after we die,38.61,Portkey,171.48,Potion that smells of plums and chocolates,By a difficult exam,Werewolves,NaN,25.87,Ravenclaw
3,4,28.0,Muggle Born,36.0,F,Magical Creatures,47.50,Portkey,142.18,Potion that makes you see strange visions,I choose students with high scores,Centaurs,NaN,82.35,Slytherine
4,5,28.0,Muggle Born,40.0,F,Plants,54.29,Flying,190.82,Potion that smells of plums and chocolates,By a difficult exam,Humans,NaN,95.46,Ravenclaw
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,29.0,Pure Blood,35.0,F,World after we die,54.78,Portkey,189.10,Silvery Potion,By a psychological test,Centaurs,NaN,47.64,Slytherine
1996,1997,30.0,Pure Blood,40.0,M,Magical Creatures,45.42,Flying,167.52,Silvery Potion,I choose students with high scores,Humans,NaN,59.04,Slytherine
1997,1998,33.0,Pure Blood,41.0,M,Plants,28.53,Floo Network,151.23,Potion that smells of plums and chocolates,I choose without preferences,Centaurs,NaN,48.47,Ravenclaw
1998,1999,30.0,Muggle Born,40.0,M,World after we die,73.57,Apparition,177.57,Potion that smells of plums and chocolates,I choose without preferences,Werewolves,NaN,67.51,Hufflepuff
1999,2000,30.0,Muggle Born,39.0,F,Plants,54.18,Apparition,126.43,Potion that smells of plums and chocolates,By a psychological test,Humans,NaN,27.17,Slytherine

this is for cigarette question

In [ ]:
import pandas as pd

# Assuming you have a DataFrame named 'df'
df2= pd.read_csv('/content/acp-r1-r12-2016-2022-v1.6.csv', encoding='latin-1')
# Example using a DataFrame
num_rows, num_columns = df2.shape

print(f"Number of Rows: {num_rows}")
print(f"Number of Columns: {num_columns}")

Number of Rows: 215449
Number of Columns: 28

<ipython-input-20-f5069ecf005b>:4: DtypeWarning: Columns (0,1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2= pd.read_csv('/content/acp-r1-r12-2016-2022-v1.6.csv', encoding='latin-1')

In [ ]:
df2

,Store_ID,Round,Fieldworker_Code,Country,Currency,Day,Month,Year,Date,Province,...,Quantity,Unusual_Quantity_Flg,Local_Price,Local_Price_Per_Stick_Cigarette,Dollar_Exchange_Rate,Dollar_Price,Dollar_Price_Per_Stick_Cigarett,Dollar_Price_Pack_Cigarettes,Fieldworker_Comment,Data_Cleaner_Comment
0,123.0,1,F,Lesotho,LSL,18.0,1.0,2016.0,18jan2016,Lowlands,...,1.0,0.0,2.50,2.5000,16.3000,0.153374,0.153374,3.067485,NaN,NaN
1,51.0,1,B,Namibia,NAD,18.0,1.0,2016.0,18jan2016,Khomas,...,20.0,0.0,20.00,1.0000,16.3000,1.226994,0.061350,1.226994,NaN,NaN
2,51.0,1,B,Namibia,NAD,18.0,1.0,2016.0,18jan2016,Khomas,...,20.0,0.0,36.99,1.8495,16.3000,2.269325,0.113466,2.269325,NaN,NaN
3,52.0,1,B,Namibia,NAD,19.0,1.0,2016.0,19jan2016,Khomas,...,20.0,0.0,37.00,1.8500,16.3000,2.269939,0.113497,2.269939,NaN,NaN
4,33.0,1,A,Uganda,UGX,22.0,1.0,2016.0,22jan2016,Central Uganda,...,20.0,0.0,3500.00,175.0000,3440.9000,1.017176,0.050859,1.017176,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215444,416.0,12,251,Lesotho,LSL,20.0,7.0,2022.0,20jul2022,Maseru,...,1.0,0.0,1.00,1.0000,15.4713,0.064636,0.064636,1.292716,NaN,NaN
215445,449.0,12,251,Lesotho,LSL,20.0,7.0,2022.0,20jul2022,Maseru,...,1.0,0.0,2.50,2.5000,15.4713,0.161590,0.161590,3.231791,NaN,NaN
215446,17.0,12,309,Zimbabwe,ZAR,20.0,7.0,2022.0,20jul2022,Matebeleland,...,1.0,0.0,1.00,1.0000,14.6785,0.068127,0.068127,1.362537,NaN,NaN
215447,608.0,12,277,Lesotho,LSL,19.0,7.0,2022.0,19jul2022,Maseru,...,1.0,0.0,3.00,3.0000,15.4713,0.193907,0.193907,3.878149,NaN,NaN
215448,659.0,12,301,Zimbabwe,BOND,28.0,6.0,2022.0,28jun2022,Masvingo,...,1.0,0.0,20.00,20.0000,101.1960,0.197636,0.197636,3.952725,NaN,NaN

In [ ]:
namibia=df2[df2['Country']=="Namibia"]
namibia

,Store_ID,Round,Fieldworker_Code,Country,Currency,Day,Month,Year,Date,Province,...,Quantity,Unusual_Quantity_Flg,Local_Price,Local_Price_Per_Stick_Cigarette,Dollar_Exchange_Rate,Dollar_Price,Dollar_Price_Per_Stick_Cigarett,Dollar_Price_Pack_Cigarettes,Fieldworker_Comment,Data_Cleaner_Comment
1,51.0,1,B,Namibia,NAD,18.0,1.0,2016.0,18jan2016,Khomas,...,20.0,0.0,20.00,1.0000,16.30000,1.226994,0.061350,1.226994,NaN,NaN
2,51.0,1,B,Namibia,NAD,18.0,1.0,2016.0,18jan2016,Khomas,...,20.0,0.0,36.99,1.8495,16.30000,2.269325,0.113466,2.269325,NaN,NaN
3,52.0,1,B,Namibia,NAD,19.0,1.0,2016.0,19jan2016,Khomas,...,20.0,0.0,37.00,1.8500,16.30000,2.269939,0.113497,2.269939,NaN,NaN
20,51.0,1,B,Namibia,NAD,18.0,1.0,2016.0,18jan2016,Khomas,...,20.0,0.0,26.99,1.3495,16.30000,1.655828,0.082791,1.655828,NaN,NaN
21,51.0,1,B,Namibia,NAD,18.0,1.0,2016.0,18jan2016,Khomas,...,20.0,0.0,36.99,1.8495,16.30000,2.269325,0.113466,2.269325,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200140,1378.0,11,307,Namibia,NAD,22.0,1.0,2022.0,22jan2022,Khomas,...,20.0,0.0,52.60,2.6300,15.57465,3.377283,0.168864,3.377283,NaN,NaN
200158,1366.0,11,281,Namibia,NAD,6.0,1.0,2022.0,06jan2022,Khomas,...,50.0,0.0,40.00,0.8000,15.57465,2.568276,0.051366,1.027310,grams,NaN
200167,1207.0,11,307,Namibia,NAD,30.0,12.0,2021.0,30dec2021,Oshana Region,...,20.0,0.0,32.99,1.6495,15.57465,2.118186,0.105909,2.118186,NaN,NaN
200172,1327.0,11,281,Namibia,NAD,23.0,12.0,2021.0,23dec2021,Khomas,...,20.0,0.0,32.00,1.6000,15.57465,2.054621,0.102731,2.054621,NaN,NaN
200181,1205.0,11,307,Namibia,NAD,30.0,12.0,2021.0,30dec2021,Oshana Region,...,20.0,0.0,45.99,2.2995,15.57465,2.952875,0.147644,2.952875,NaN,NaN

In [ ]:
import pandas as pd

# Load your Hogwarts Houses dataset
# Replace 'hogwarts_dataset.csv' with the actual filename or path to your dataset
hogwarts_data = pd.read_csv('/content/harry_potter.csv')

# Assuming your dataset has columns like 'House' and 'Kindness'
# Calculate the mean kindness for each house
average_kindness_per_house = hogwarts_data.groupby('House')['Kindness'].mean()

# Find the house with the highest average kindness
house_with_highest_kindness = average_kindness_per_house.idxmax()
highest_kindness_value = average_kindness_per_house.max()

# Display the result
rounded_off_mean_kindness = round(highest_kindness_value, 2)
print(f"{house_with_highest_kindness}, {rounded_off_mean_kindness}")

Hufflepuff, 51.56

In [ ]:

slytherin_data = hogwarts_data[hogwarts_data['House'] == 'Slytherin']

# Check if there is any data for Slytherin
if not slytherin_data.empty:
    # Calculate the mean affinity to Dark Arts for Slytherin
    average_affinity_slytherin = slytherin_data['Affinity to Dark Arts'].mean()

    # Display the result
    rounded_off_affinity_slytherin = round(average_affinity_slytherin, 2)
    print(f"The average affinity to Dark Arts for Slytherin house is: {rounded_off_affinity_slytherin}")
else:
    print("No data available for Slytherin house.")

No data available for Slytherin house.

In [ ]:
import pandas as pd

# Replace 'your_dataset.csv' with the actual path or URL of your dataset
df = pd.read_csv('/content/acp-r1-r12-2016-2022-v1.6.csv', encoding="latin")

# Filter data for the suburb 'Windhoek West'
windhoek_west_data = df[df['Suburb'] == 'Windhoek West']

# Count the number of unique cigarette brands in Windhoek West
unique_brands_count = windhoek_west_data['Brand'].nunique()

print(f"Total number of unique cigarette brands in Windhoek West: {unique_brands_count}")

Total number of unique cigarette brands in Windhoek West: 22

<ipython-input-73-d385ea18d30d>:4: DtypeWarning: Columns (0,1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/acp-r1-r12-2016-2022-v1.6.csv', encoding="latin")